export const PRESETS = [
  { id: "potes", label: "Les potes (têtes)", title: "Les meilleurs potes", items: null },
  { id: "pizzas", label: "Pizzas", title: "Les meilleures pizzas", items: ["Margherita", "Reine", "4 fromages", "Calzone", "Hawaïenne", "Chorizo", "Végétarienne", "Chèvre miel", "Pepperoni", "Orientale", "Norvégienne", "Burger"] },
  { id: "fastfood", label: "Fast-foods", title: "Les fast-foods", items: ["McDo", "Burger King", "KFC", "Quick", "Subway", "Five Guys", "Tacos", "Kebab", "Domino's", "Pizza Hut", "Pitaya", "Panda Wok"] },
  { id: "jeux", label: "Jeux vidéo", title: "Les jeux vidéo", items: ["Minecraft", "Fortnite", "League of Legends", "Mario Kart", "FIFA", "GTA", "Zelda", "Pokémon", "Call of Duty", "Among Us", "Valorant", "Rocket League", "Smash Bros", "Les Sims"] },
  { id: "boissons", label: "Boissons", title: "Les boissons", items: ["Eau", "Coca", "Fanta", "Ice Tea", "Sirop", "Jus d'orange", "Café", "Thé", "Limonade", "Chocolat chaud", "Smoothie", "Perrier"] },
  { id: "snacks", label: "Snacks", title: "Les snacks", items: ["Chips", "Kinder Bueno", "Haribo", "Cacahuètes", "Pop-corn", "Biscuits", "Nutella", "Gaufres", "Oreo", "Tuc", "Crêpes", "Bonbons acides"] },
  { id: "sauces", label: "Sauces", title: "Les sauces", items: ["Ketchup", "Mayonnaise", "Moutarde", "Algérienne", "Samouraï", "Barbecue", "Biggy", "Harissa", "Andalouse", "Blanche", "Curry", "Poivre"] },
  { id: "animaux", label: "Animaux", title: "Les animaux", items: ["Chien", "Chat", "Panda", "Pingouin", "Requin", "Pigeon", "Loutre", "Lama", "Flamant rose", "Capybara", "Poulpe", "Hérisson"] },
  { id: "jours", label: "Jours de la semaine", title: "Les jours de la semaine", items: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"] },
  { id: "saisons", label: "Saisons et mois", title: "Les mois de l'année", items: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"] },
  { id: "dessins", label: "Dessins animés", title: "Les dessins animés", items: ["Bob l'éponge", "Les Simpson", "Dragon Ball", "Naruto", "One Piece", "Tom et Jerry", "Pokémon", "Totally Spies", "Kirikou", "Ratatouille", "Shrek", "Toy Story"] },
  { id: "films", label: "Genres de films", title: "Les genres de films", items: ["Action", "Comédie", "Horreur", "Science-fiction", "Romance", "Animation", "Thriller", "Documentaire", "Fantasy", "Policier", "Western", "Comédie musicale"] },
  { id: "activites", label: "Activités de soirée", title: "Les activités de soirée", items: ["Jeux de société", "Karaoké", "Cinéma", "Bowling", "Barbecue", "Escape game", "Blind test", "Jeux vidéo", "Soirée pizza", "Billard", "Ballade", "Cartes"] },
  { id: "bruits", label: "Bruits du quotidien", title: "Les bruits du quotidien", items: ["Réveil", "Craie sur tableau", "Pluie", "Moto", "Tondeuse", "Éternuement", "Mouche", "Perceuse du voisin", "Bébé", "Notification", "Sonnette", "Alarme"] },
  { id: "metiers", label: "Métiers", title: "Les métiers", items: ["Boulanger", "Pompier", "Astronaute", "Youtubeur", "Plombier", "Pilote", "Médecin", "Footballeur", "Facteur", "Chef cuisinier", "Maître-nageur", "Dev web"] },
  { id: "sports", label: "Sports", title: "Les sports", items: ["Football", "Basket", "Tennis", "Natation", "Rugby", "Pétanque", "Escalade", "Ping-pong", "Golf", "Boxe", "Ski", "Danse"] },
  { id: "fruits", label: "Fruits et légumes", title: "Les fruits et légumes", items: ["Fraise", "Banane", "Pomme", "Mangue", "Brocoli", "Carotte", "Tomate", "Ananas", "Raisin", "Concombre", "Cerise", "Aubergine"] },
  { id: "cantine", label: "Plats de cantine", title: "Les plats de cantine", items: ["Purée", "Steak haché", "Poisson pané", "Lasagnes", "Haricots verts", "Semoule", "Cordon bleu", "Frites", "Compote", "Yaourt", "Gratin", "Épinards"] },
  { id: "pays", label: "Pays à visiter", title: "Les pays à visiter", items: ["Japon", "Italie", "Espagne", "États-Unis", "Islande", "Mexique", "Canada", "Grèce", "Thaïlande", "Portugal", "Norvège", "Australie"] },
  { id: "excuses", label: "Excuses de retard", title: "Les excuses de retard", items: ["Panne de réveil", "Transports", "J'ai perdu mes clés", "Trop de monde", "Mon chat", "Je suis déjà là", "Problème de GPS", "Dernière partie", "Mon téléphone", "Embouteillage", "J'arrive", "Je dormais"] },
  { id: "emotions", label: "Humeurs", title: "Les humeurs", items: ["Fatigué", "Affamé", "Motivé", "Zen", "Énervé", "Nostalgique", "Pressé", "Gêné", "Sur le canapé", "Hyperactif", "Inspiré", "Philosophe"] },
  { id: "objets", label: "Objets du quotidien", title: "Les objets du quotidien", items: ["Téléphone", "Chargeur", "Écouteurs", "Clés", "Parapluie", "Sac à dos", "Lunettes", "Montre", "Ordinateur", "Manette", "Couette", "Frigo"] },
];
