export const WEAPONS = {
  pistol: {
    id: "pistol",
    name: "Pistolet",
    price: 0,
    cooldown: 0.17,
    damage: 1,
    pellets: 1,
    spread: 0.012,
    speed: 950,
    pierce: 0,
    range: 1400,
    tracer: "#ffe9a0",
    recoil: 1,
    desc: "Fiable et précis. Là où tout commence.",
  },
  shotgun: {
    id: "shotgun",
    name: "Fusil à pompe",
    price: 400,
    cooldown: 0.62,
    damage: 1,
    pellets: 7,
    spread: 0.26,
    speed: 850,
    pierce: 0,
    range: 390,
    tracer: "#ffb35a",
    recoil: 2.4,
    desc: "7 plombs en éventail. Dévastateur de près.",
  },
  smg: {
    id: "smg",
    name: "Mitraillette",
    price: 800,
    cooldown: 0.075,
    damage: 1,
    pellets: 1,
    spread: 0.055,
    speed: 1000,
    pierce: 0,
    range: 1400,
    tracer: "#ffe27a",
    recoil: 0.7,
    desc: "Cadence folle, précision moyenne.",
  },
  rifle: {
    id: "rifle",
    name: "Fusil d'assaut",
    price: 1500,
    cooldown: 0.11,
    damage: 2,
    pellets: 1,
    spread: 0.02,
    speed: 1150,
    pierce: 0,
    range: 1500,
    tracer: "#fff0b0",
    recoil: 1.2,
    desc: "2 dégâts par balle. Redoutable contre les gilets.",
  },
  sniper: {
    id: "sniper",
    name: "Fusil de précision",
    price: 2500,
    cooldown: 0.8,
    damage: 6,
    pellets: 1,
    spread: 0,
    speed: 1700,
    pierce: 99,
    range: 1800,
    tracer: "#bff3ff",
    recoil: 3,
    desc: "Transperce tout ce qui est aligné. Un tir lent, 6 dégâts.",
  },
  minigun: {
    id: "minigun",
    name: "Minigun",
    price: 4000,
    cooldown: 0.042,
    damage: 1,
    pellets: 1,
    spread: 0.1,
    speed: 1050,
    pierce: 0,
    range: 1400,
    tracer: "#ffd24d",
    recoil: 0.5,
    desc: "Un mur de plomb pour les grosses vagues.",
  },
};

export const ORDER = ["pistol", "shotgun", "smg", "rifle", "sniper", "minigun"];

export const TURRETS = [
  { name: "Tourelle n°1", price: 600, desc: "Se déploie à gauche de la frontière et tire seule." },
  { name: "Tourelle n°2", price: 1500, desc: "Une deuxième tourelle, à droite." },
  { name: "Tourelle n°3", price: 3000, desc: "Une troisième, au centre. Le mur défensif." },
];

export const TURRET_WEAPON = {
  speed: 820,
  damage: 1,
  spread: 0,
  pierce: 0,
  range: 1100,
  tracer: "#8ff0ff",
  cooldown: 0.5,
};

export const COINS = { normal: 5, runner: 8, vest: 15 };

export const MINE_UPGRADES = {
  count: {
    name: "Champ de mines",
    desc: "Nombre de mines posées au début de chaque vague.",
    values: [0, 3, 5, 7, 10, 14],
    prices: [400, 700, 1100, 1700, 2600],
    format: (value) => (value ? `${value} mines` : "Aucune"),
  },
  damage: {
    name: "Charge explosive",
    desc: "Dégâts infligés par chaque explosion.",
    values: [4, 6, 9, 13, 18, 25],
    prices: [500, 900, 1500, 2400, 3800],
    format: (value) => `${value} dégâts`,
  },
  radius: {
    name: "Rayon de souffle",
    desc: "Taille de la zone touchée par l'explosion.",
    values: [55, 70, 85, 100, 120, 145],
    prices: [400, 700, 1100, 1700, 2600],
    format: (value) => `${value} px`,
  },
  rearm: {
    name: "Repose automatique",
    desc: "Délai pour reposer une mine explosée pendant la vague.",
    values: [0, 12, 9, 6, 4, 2],
    prices: [800, 1400, 2200, 3500, 5500],
    format: (value) => (value ? `${value} s` : "Au début de la vague"),
  },
};

export const MINE_KEYS = ["count", "damage", "radius", "rearm"];
