export const SITE = {
  name: "LE QG",
  tagline: "Des jeux, des memes et de la mauvaise foi. Rien à acheter.",
  announce: "Site privé entre potes — réservé à la bande",
};

export const NAV = [
  { label: "Accueil", href: "index.html", page: "home" },
  { label: "Jeux", href: "jeux.html", page: "jeux" },
  { label: "Outils", href: "outils.html", page: "outils" },
  { label: "Memes", href: "memes.html", page: "memes" },
];

const PHOTOS = [
  "assets/heads/tete-1.png",
  "assets/heads/tete-2.png",
  "assets/heads/tete-3.png",
  "assets/heads/tete-4.png",
  "assets/police/policier-1.png",
  "assets/police/policier-2.png",
  "assets/police/policier-3.png",
  "assets/heads/tete-5.png",
  "assets/heads/tete-6.png",
  "assets/heads/tete-7.png",
  "assets/heads/tete-8.png",
  "assets/heads/tete-9.png",
  "assets/heads/tete-10.png",
  "assets/heads/tete-11.png",
  "assets/heads/tete-12.png",
  "assets/heads/tete-13.png",
  "assets/heads/tete-14.png",
  "assets/heads/tete-15.png",
  "assets/heads/tete-16.png",
  "assets/heads/tete-17.png",
  "assets/heads/tete-18.png",
  "assets/heads/tete-19.png",
  "assets/heads/tete-20.png",
  "assets/heads/tete-21.png",
  "assets/heads/tete-22.png",
  "assets/heads/tete-23.png",
  "assets/heads/tete-24.png",
  "assets/heads/tete-25.png",
  "assets/heads/tete-26.png",
  "assets/heads/tete-27.png",
];

export const MEME_EXTRAS = ["assets/memes/soixante-sept.png"];

export const HEADS = PHOTOS;

export const POLICE = PHOTOS;

export const BACKGROUNDS = [
  { id: "ocean", label: "Océan", a: "#0f4c75", b: "#3282b8" },
  { id: "sunset", label: "Coucher", a: "#c0392b", b: "#f39c12" },
  { id: "lime", label: "Citron", a: "#1e8449", b: "#b7e44a" },
  { id: "violet", label: "Violet", a: "#4a235a", b: "#af7ac5" },
  { id: "graphite", label: "Graphite", a: "#17202a", b: "#566573" },
  { id: "sand", label: "Sable", a: "#b9770e", b: "#f5cba7" },
  { id: "fire", label: "Feu", a: "#7f0000", b: "#ff6a00" },
  { id: "candy", label: "Bonbon", a: "#d63384", b: "#ffb3d9" },
  { id: "night", label: "Nuit", a: "#0b1026", b: "#3b4a9a" },
  { id: "mint", label: "Menthe", a: "#0f766e", b: "#99f6e4" },
  { id: "gold", label: "Or", a: "#8a6a00", b: "#ffe066" },
  { id: "steel", label: "Acier", a: "#2d3748", b: "#cbd5e0" },
  { id: "photo-gros-caca", label: "Photo : gros caca", a: "#a89968", b: "#e8dca8", image: "assets/photos/gros-caca.jpg", focus: 0.2 },
  { id: "photo-chapeau", label: "Photo : chapeau", a: "#8b1a3a", b: "#f2b5c4", image: "assets/photos/chapeau.jpg", focus: 0.5 },
  { id: "photo-cri", label: "Photo : le cri", a: "#555", b: "#ddd", image: "assets/photos/cri.jpg", focus: 0.5 },
  { id: "photo-webcam", label: "Photo : webcam", a: "#888", b: "#eee", image: "assets/photos/webcam.jpg", focus: 0.3 },
  { id: "photo-moustache", label: "Photo : moustache", a: "#7a4a3a", b: "#d9a08c", image: "assets/photos/moustache.jpg", focus: 0.3 },
  { id: "photo-cri-noir", label: "Photo : cri dans le noir", a: "#101810", b: "#dfeedd", image: "assets/photos/cri-noir.jpg", focus: 0.4 },
  { id: "photo-lunettes", label: "Photo : lunettes de nuit", a: "#0b1a3a", b: "#4cc9e0", image: "assets/photos/lunettes.jpg", focus: 0.5 },
  { id: "photo-concombres", label: "Photo : concombres", a: "#4d6b2a", b: "#b9d68b", image: "assets/photos/concombres.jpg", focus: 0.4 },
  { id: "photo-oasis", label: "Photo : Oasis", a: "#c9792b", b: "#f3d9a8", image: "assets/photos/oasis.jpg", focus: 0.5 },
  { id: "photo-chemise-rose", label: "Photo : chemise rose", a: "#c97b8f", b: "#f4d6dc", image: "assets/photos/chemise-rose.jpg", focus: 0.3 },
];

export const MEMES = [
  { head: 0, bg: "ocean", top: "Moi quand je dis", bottom: "J'arrive dans 5 minutes" },
  { head: 1, bg: "graphite", top: "Le groupe quand quelqu'un", bottom: "propose un plan" },
  { head: 2, bg: "sunset", top: "Ma tête quand", bottom: "le wifi coupe en pleine partie" },
  { head: 3, bg: "lime", top: "POV : t'as perdu", bottom: "à ton propre jeu" },
  { head: 0, bg: "violet", top: "Tout le monde dort", bottom: "moi à 4h du mat sur Discord" },
  { head: 2, bg: "sand", top: "Quand tu dis \"c'est ma tournée\"", bottom: "et que t'as plus de sous" },
  { head: 1, bg: "ocean", top: "Le mec qui lit le message", bottom: "et répond jamais" },
  { head: 3, bg: "sunset", top: "Moi après une victoire", bottom: "contre un débutant" },
  { head: 0, bg: "fire", top: "Moi qui dis « deux minutes »", bottom: "et qui disparais pendant 2 heures" },
  { head: 1, bg: "candy", top: "Quand la pizza arrive", bottom: "et que tout le monde devient ton ami" },
  { head: 2, bg: "night", top: "3 h du matin", bottom: "je repense à mes mauvaises décisions de 2014" },
  { head: 3, bg: "mint", top: "Le groupe : « on se voit quand ? »", bottom: "Tout le monde : « jamais, mais avec plaisir »" },
  { head: 0, bg: "gold", top: "Moi, expert en tout", bottom: "après avoir regardé une vidéo de 4 minutes" },
  { head: 1, bg: "steel", top: "Quand quelqu'un dit « j'ai une idée »", bottom: "et que tu sais déjà comment ça finit" },
  { head: 2, bg: "fire", top: "Mon compte en banque", bottom: "le 28 du mois" },
  { head: 3, bg: "ocean", top: "Moi à la fin d'une soirée", bottom: "« Allez, on en refait une ! »" },
  { head: 0, bg: "sunset", top: "Quand on te demande", bottom: "« tu fais quoi ce week-end ? »" },
  { head: 1, bg: "violet", top: "Le mec qui lit « vu »", bottom: "et vit sa meilleure vie" },
  { head: 2, bg: "candy", top: "Ma motivation un lundi", bottom: "contre mon canapé" },
  { head: 3, bg: "night", top: "Les potes qui savent", bottom: "que tu vas encore être en retard" },
  { head: 0, bg: "lime", top: "Quand t'as raison", bottom: "mais que personne n'est là pour le voir", layout: "banniere" },
  { head: 1, bg: "graphite", top: "Moi qui prépare un plan sérieux", bottom: "le plan : improviser", layout: "banniere" },
  { head: 2, bg: "steel", top: "Le wifi de la maison", bottom: "pendant que je télécharge un jeu", layout: "banniere" },
  { head: 3, bg: "gold", top: "Quand on te dit « c'est ton tour »", bottom: "et que tu n'écoutais pas", layout: "banniere" },
  { head: 0, bg: "mint", top: "Une dernière partie, promis", bottom: "(il est 5 h)", layout: "banniere" },
  { head: 1, bg: "fire", top: "Moi sur le canapé", bottom: "contre toute la journée", layout: "banniere" },
  { head: 0, bg: "ocean", top: "Rester chez moi", bottom: "Sortir avec les potes", layout: "drake", head2: 1 },
  { head: 1, bg: "violet", top: "Faire le ménage", bottom: "Rejouer une partie de plus", layout: "drake", head2: 2 },
  { head: 2, bg: "sunset", top: "Répondre aux messages", bottom: "Mettre le téléphone en silencieux", layout: "drake", head2: 3 },
  { head: 3, bg: "night", top: "Cuisiner", bottom: "Commander une pizza", layout: "drake", head2: 0 },
  { head: 0, bg: "fire", top: "Se coucher tôt", bottom: "Regarder une série jusqu'à 3 h", layout: "drake", head2: 1 },
  { head: 1, bg: "lime", top: "Le canapé", bottom: "Moi, quand il faut se lever", layout: "versus", head2: 2 },
  { head: 2, bg: "candy", top: "Mon réveil", bottom: "Ma volonté", layout: "versus", head2: 3 },
  { head: 3, bg: "steel", top: "Le dernier morceau de pizza", bottom: "Tout le monde, en silence", layout: "versus", head2: 0 },
  { head: 0, bg: "gold", top: "Moi, le dimanche soir", bottom: "Moi, le lundi matin", layout: "versus", head2: 1 },
  { head: 1, bg: "mint", top: "Le groupe de potes", bottom: "Le seul qui répond", layout: "versus", head2: 2 },
];

export const GAMES = [
  {
    slug: "kill-all-the-jules",
    title: "Kill all the Jules",
    text: "Défends la frontière entre la Zone A et la Zone B. Vagues d'intrus, boss géant, véhicules, arsenal, tourelles et mines.",
    href: "jeu.html",
    image: "assets/jeu-apercu.jpg",
    badge: "Star",
    tags: ["Action", "Boss", "Arsenal"],
  },
  {
    slug: "flappy",
    title: "Flappy Tête",
    text: "Une tête qui bat des ailes entre des tuyaux. Simple, cruel, addictif.",
    href: "flappy.html",
    image: "assets/previews/flappy.jpg",
    badge: "",
    tags: ["Arcade", "Record"],
  },
  {
    slug: "taupe",
    title: "Tape-Tête",
    text: "Des têtes sortent des trous, tu les bonkes au marteau. Têtes dorées et combos.",
    href: "taupe.html",
    image: "assets/previews/taupe.jpg",
    badge: "",
    tags: ["Réflexes", "45 secondes"],
  },
  {
    slug: "serpent",
    title: "Serpent gourmand",
    text: "Le classique serpent, mais il mange des têtes. Il accélère à chaque palier.",
    href: "serpent.html",
    image: "assets/previews/serpent.jpg",
    badge: "",
    tags: ["Classique", "Record"],
  },
  {
    slug: "memory",
    title: "Memory de la bande",
    text: "Retrouve les paires de têtes en un minimum de coups. Trois niveaux.",
    href: "memory.html",
    image: "assets/previews/memory.jpg",
    badge: "",
    tags: ["Réflexion", "3 niveaux"],
  },
  {
    slug: "clicker",
    title: "Tête Clicker",
    text: "Clique sur la tête, gagne des likes, achète des chaînes YouTube et des concerts.",
    href: "clicker.html",
    image: "assets/previews/clicker.jpg",
    badge: "",
    tags: ["Idle", "Sauvegarde auto"],
  },
  {
    slug: "casse",
    title: "Casse-Tête",
    text: "Un casse-briques dont les briques sont des têtes. Bonus, vies et niveaux.",
    href: "casse.html",
    image: "assets/previews/casse.jpg",
    badge: "",
    tags: ["Arcade", "Bonus"],
  },
  {
    slug: "deuxmille",
    title: "2048 des potes",
    text: "Fusionne les têtes identiques jusqu'à la tête ultime.",
    href: "deuxmille.html",
    image: "assets/previews/deuxmille.jpg",
    badge: "",
    tags: ["Réflexion", "Record"],
  },
  {
    slug: "mot",
    title: "Mot-Tête",
    text: "Un Wordle en français, avec un mot du jour pour toute la bande.",
    href: "mot.html",
    image: "assets/previews/mot.jpg",
    badge: "",
    tags: ["Mots", "Quotidien"],
  },
  {
    slug: "puissance4",
    title: "Puissance 4",
    text: "Aligne quatre têtes contre l'ordinateur ou contre un pote.",
    href: "puissance4.html",
    image: "assets/previews/puissance4.jpg",
    badge: "",
    tags: ["Duel", "IA"],
  },
  {
    slug: "course",
    title: "Course de têtes",
    text: "Parie sur ton coureur, regarde la course, quitte ou double.",
    href: "course.html",
    image: "assets/previews/course.jpg",
    badge: "",
    tags: ["Paris", "Cagnotte"],
  },
  {
    slug: "reflexes",
    title: "Réflexes et clics",
    text: "Ton temps de réaction et ton nombre de clics par seconde.",
    href: "reflexes.html",
    image: "assets/previews/reflexes.jpg",
    badge: "",
    tags: ["Réflexes", "Défi"],
  },
  {
    slug: "demineur",
    title: "Démineur",
    text: "Ouvre les cases sans réveiller les têtes cachées dessous.",
    href: "demineur.html",
    image: "assets/previews/demineur.jpg",
    badge: "",
    tags: ["Réflexion", "3 niveaux"],
  },
  {
    slug: "rythme",
    title: "Rythme des potes",
    text: "Des flèches en rythme avec les vidéos du QG : des dizaines de morceaux, 4 difficultés.",
    href: "rythme.html",
    image: "assets/previews/rythme.jpg",
    badge: "Nouveau",
    tags: ["Rythme", "Vidéo", "Records"],
  },
  {
    slug: "invasion",
    title: "Invasion des têtes",
    text: "Abats les vagues de têtes avant qu'elles n'atteignent ton canon.",
    href: "invasion.html",
    image: "assets/previews/invasion.jpg",
    badge: "Nouveau",
    tags: ["Arcade", "Tir", "Vagues"],
  },
  {
    slug: "pong",
    title: "Ping-pong des têtes",
    text: "Un match de pong contre la machine, avec une tête en guise de balle.",
    href: "pong.html",
    image: "assets/previews/pong.jpg",
    badge: "Nouveau",
    tags: ["Arcade", "1 joueur"],
  },
  {
    slug: "slots",
    title: "Machine à sous",
    text: "Trois têtes, des jetons de mauvaise foi, aucun vrai argent.",
    href: "slots.html",
    image: "assets/previews/slots.jpg",
    badge: "Nouveau",
    tags: ["Casino", "Hasard"],
  },
  {
    slug: "zoomtete",
    title: "Zoom tête",
    text: "Un détail agrandi d'une tête : retrouve laquelle avant la fin du chrono.",
    href: "zoomtete.html",
    image: "assets/previews/zoomtete.jpg",
    badge: "Nouveau",
    tags: ["Quiz", "Vitesse"],
  },
  {
    slug: "erreurs",
    title: "Les cinq erreurs",
    text: "Deux photos presque identiques : trouve les différences, manche après manche.",
    href: "erreurs.html",
    image: "assets/previews/erreurs.jpg",
    badge: "Nouveau",
    tags: ["Observation", "Photos"],
  },
  {
    slug: "blindtest",
    title: "Blind test des potes",
    text: "Un extrait de quelques secondes, quatre titres : de quelle vidéo ça vient ?",
    href: "blindtest.html",
    image: "assets/previews/blindtest.jpg",
    badge: "Nouveau",
    tags: ["Quiz", "Son"],
  },
  {
    slug: "simon",
    title: "Simon des potes",
    text: "Retiens la suite de têtes qui s'allument et rejoue-la.",
    href: "simon.html",
    image: "assets/previews/simon.jpg",
    badge: "",
    tags: ["Mémoire", "Record"],
  },
  {
    slug: "pfc",
    title: "Pierre, feuille, ciseaux",
    text: "Le classique contre l'ordinateur, premier à cinq points.",
    href: "pfc.html",
    image: "assets/previews/pfc.jpg",
    badge: "",
    tags: ["Duel", "Rapide"],
  },
  {
    slug: "pendu",
    title: "Pendu",
    text: "Trouve le mot avant que le dessin soit complet, avec des thèmes.",
    href: "pendu.html",
    image: "assets/previews/pendu.jpg",
    badge: "",
    tags: ["Mots", "Série"],
  },
  {
    slug: "aim",
    title: "Tire-Tête",
    text: "Un entraînement de précision : clique les têtes avant qu'elles disparaissent.",
    href: "aim.html",
    image: "assets/previews/aim.jpg",
    badge: "",
    tags: ["Précision", "30 secondes"],
  },
  {
    slug: "taquin",
    title: "Taquin",
    text: "Remets les morceaux de la tête dans l'ordre.",
    href: "taquin.html",
    image: "assets/previews/taquin.jpg",
    badge: "",
    tags: ["Puzzle", "2 tailles"],
  },
  {
    slug: "tetris",
    title: "Tétris des potes",
    text: "Empile des blocs à tête, complète des lignes, bats ton record.",
    href: "tetris.html",
    image: "assets/previews/tetris.jpg",
    badge: "Nouveau",
    tags: ["Arcade", "Classique"],
  },
  {
    slug: "runner",
    title: "Cours, Tête !",
    text: "Un runner sans fin : saute les cactus, baisse-toi sous les oiseaux.",
    href: "runner.html",
    image: "assets/previews/runner.jpg",
    badge: "Nouveau",
    tags: ["Arcade", "Endless"],
  },
  {
    slug: "ballons",
    title: "Crève-ballons",
    text: "Éclate des ballons à tête avant qu'ils s'envolent. Attention aux bombes.",
    href: "ballons.html",
    image: "assets/previews/ballons.jpg",
    badge: "Nouveau",
    tags: ["Arcade", "Réflexes"],
  },
  {
    slug: "morpion",
    title: "Morpion des têtes",
    text: "Trois têtes alignées gagnent. Contre la machine ou à deux.",
    href: "morpion.html",
    image: "assets/previews/morpion.jpg",
    badge: "Nouveau",
    tags: ["Duel", "IA"],
  },
  {
    slug: "blackjack",
    title: "Blackjack des potes",
    text: "Approche-toi de 21 sans le dépasser. Jetons fictifs.",
    href: "blackjack.html",
    image: "assets/previews/blackjack.jpg",
    badge: "Nouveau",
    tags: ["Casino", "Cartes"],
  },
  {
    slug: "chrono10",
    title: "Chrono 10 secondes",
    text: "Arrête le chrono pile sur 10,00 s. Cinq essais, le moins d'écart gagne.",
    href: "chrono10.html",
    image: "assets/previews/chrono10.jpg",
    badge: "Nouveau",
    tags: ["Précision", "Défi"],
  },
  {
    slug: "dactylo",
    title: "Dactylo des potes",
    text: "Recopie trois phrases absurdes le plus vite possible.",
    href: "dactylo.html",
    image: "assets/previews/dactylo.jpg",
    badge: "Nouveau",
    tags: ["Vitesse", "Clavier"],
  },
  {
    slug: "silhouette",
    title: "Qui est dans l'ombre ?",
    text: "Une tête dans le noir qui s'éclaire peu à peu : devine laquelle.",
    href: "silhouette.html",
    image: "assets/previews/silhouette.jpg",
    badge: "Nouveau",
    tags: ["Quiz", "Vitesse"],
  },
  {
    slug: "videodevine",
    title: "Devine la vidéo",
    text: "Une image pixelisée qui se précise : retrouve la vidéo d'origine.",
    href: "videodevine.html",
    image: "assets/previews/videodevine.jpg",
    badge: "Nouveau",
    tags: ["Quiz", "Vidéo"],
  },
  {
    slug: "saute",
    title: "Saute-Tête",
    text: "Rebondis de plateforme en plateforme, le plus haut possible.",
    href: "saute.html",
    image: "assets/previews/saute.jpg",
    badge: "Nouveau",
    tags: ["Arcade", "Hauteur"],
  },
  {
    slug: "tour",
    title: "Tour de têtes",
    text: "Empile des étages pile sur le précédent pour monter la tour.",
    href: "tour.html",
    image: "assets/previews/tour.jpg",
    badge: "Nouveau",
    tags: ["Arcade", "Précision"],
  },
  {
    slug: "calcul",
    title: "Calcul mental",
    text: "Additions, soustractions, multiplications, divisions : 45 secondes.",
    href: "calcul.html",
    image: "assets/previews/calcul.jpg",
    badge: "Nouveau",
    tags: ["Maths", "Vitesse"],
  },
];

export const TOOLS = [
  {
    slug: "roulette",
    title: "Roulette de la bande",
    text: "Qui paie la tournée ? Qui choisit le film ? La roue tranche.",
    href: "roulette.html",
    image: "assets/previews/roulette.jpg",
    badge: "Outil",
    tags: ["Décision", "Personnalisable"],
  },
  {
    slug: "soundboard",
    title: "Soundboard",
    text: "Vingt bruitages à balancer au pire moment : trombone triste, vine boom, sirène…",
    href: "soundboard.html",
    image: "assets/previews/soundboard.jpg",
    badge: "Outil",
    tags: ["Son", "Raccourcis clavier"],
  },
  {
    slug: "affiches",
    title: "Affiches",
    text: "Avis de recherche, employé du mois, certificat de nullité : télécharge l'affiche.",
    href: "affiches.html",
    image: "assets/previews/affiches.jpg",
    badge: "Outil",
    tags: ["Image", "Téléchargement"],
  },
  {
    slug: "tierlist",
    title: "Tier list",
    text: "Classe la bande de S à D en glissant les têtes, puis exporte l'image.",
    href: "tierlist.html",
    image: "assets/previews/tierlist.jpg",
    badge: "Outil",
    tags: ["Glisser-déposer", "Export"],
  },
  {
    slug: "excuses",
    title: "Excuses et horoscope",
    text: "Le générateur d'excuses de mauvaise foi et l'horoscope du jour.",
    href: "excuses.html",
    image: "assets/previews/excuses.jpg",
    badge: "Outil",
    tags: ["Humour", "Copier-coller"],
  },
  {
    slug: "equipes",
    title: "Tirage d'équipes",
    text: "Colle les noms, le sort répartit les équipes.",
    href: "equipes.html",
    image: "assets/previews/equipes.jpg",
    badge: "Outil",
    tags: ["Tirage", "Copier"],
  },
  {
    slug: "scores",
    title: "Tableau des scores",
    text: "Les points de la soirée, sauvegardés sur ton appareil.",
    href: "scores.html",
    image: "assets/previews/scores.jpg",
    badge: "Outil",
    tags: ["Soirée", "Sauvegarde"],
  },
  {
    slug: "des",
    title: "Dés et pile ou face",
    text: "Jusqu'à dix dés, du D4 au D100, et une pièce qui tourne.",
    href: "des.html",
    image: "assets/previews/des.jpg",
    badge: "Outil",
    tags: ["Hasard", "Dés"],
  },
  {
    slug: "actionverite",
    title: "Action ou vérité",
    text: "Des cartes à piocher pour animer la soirée.",
    href: "actionverite.html",
    image: "assets/previews/actionverite.jpg",
    badge: "Outil",
    tags: ["Soirée", "Cartes"],
  },
  {
    slug: "textes",
    title: "Générateur de textes",
    text: "Insultes de pote, surnoms, pseudos, drague nulle, prédictions et débats absurdes.",
    href: "textes.html",
    image: "assets/previews/textes.jpg",
    badge: "Outil",
    tags: ["Humour", "Copier-coller"],
  },
  {
    slug: "susceptible",
    title: "Qui est le plus susceptible de…",
    text: "Une question, un tirage au sort, un coupable désigné.",
    href: "susceptible.html",
    image: "assets/previews/susceptible.jpg",
    badge: "Outil",
    tags: ["Soirée", "Classement"],
  },
  {
    slug: "tupreferes",
    title: "Tu préfères ?",
    text: "Des dilemmes absurdes à débattre entre potes.",
    href: "tupreferes.html",
    image: "assets/previews/tupreferes.jpg",
    badge: "Outil",
    tags: ["Débat", "Soirée"],
  },
  {
    slug: "minuteur",
    title: "Minuteur et chrono",
    text: "Un minuteur avec alarme et un chronomètre avec tours.",
    href: "minuteur.html",
    image: "assets/previews/minuteur.jpg",
    badge: "Outil",
    tags: ["Défis", "Alarme"],
  },
  {
    slug: "random",
    title: "Le grand random",
    text: "Plus de vingt tirages au sort : plats, défis, faits inutiles, têtes, titres de films…",
    href: "random.html",
    image: "assets/previews/random.jpg",
    badge: "Outil",
    tags: ["Hasard", "Tout et rien"],
  },
  {
    slug: "diplome",
    title: "Générateur de diplômes",
    text: "Un diplôme officiel (et bidon) avec nom, motif et tête de ton choix, à télécharger.",
    href: "diplome.html",
    image: "assets/previews/diplome.jpg",
    badge: "Nouveau",
    tags: ["Image", "Téléchargement"],
  },
  {
    slug: "boule",
    title: "Boule magique",
    text: "Pose une question, secoue, accepte la réponse. Aucune valeur scientifique.",
    href: "boule.html",
    image: "assets/previews/boule.jpg",
    badge: "Nouveau",
    tags: ["Décision", "Hasard"],
  },
  {
    slug: "addition",
    title: "Partage de l'addition",
    text: "Qui doit combien ? Coche qui a pris quoi, le calcul est fait.",
    href: "addition.html",
    image: "assets/previews/addition.jpg",
    badge: "Nouveau",
    tags: ["Pratique", "Argent"],
  },
  {
    slug: "bingo",
    title: "Bingo de soirée",
    text: "Une grille de situations typiques à cocher au fil de la nuit.",
    href: "bingo.html",
    image: "assets/previews/bingo.jpg",
    badge: "Nouveau",
    tags: ["Soirée", "Partageable"],
  },
  {
    slug: "compatibilite",
    title: "Compatibilité",
    text: "Deux prénoms, un pourcentage sans appel, des critères absurdes.",
    href: "compatibilite.html",
    image: "assets/previews/compatibilite.jpg",
    badge: "Nouveau",
    tags: ["Humour", "Duo"],
  },
  {
    slug: "quelpote",
    title: "Quel pote es-tu ?",
    text: "Huit questions, six profils : ton rôle dans la bande.",
    href: "quelpote.html",
    image: "assets/previews/quelpote.jpg",
    badge: "Nouveau",
    tags: ["Quiz", "Profil"],
  },
  {
    slug: "stickers",
    title: "Atelier montage",
    text: "Pose des têtes et du texte sur une photo, puis télécharge.",
    href: "stickers.html",
    image: "assets/previews/stickers.jpg",
    badge: "Nouveau",
    tags: ["Image", "Téléchargement"],
  },
];
